[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 200
maxMessageSize = 500
enableCORS = false
enableXsrfProtection = false
websocketMaxMessageSize = 500

[browser]
gatherUsageStats = false

[logger]
level = "info"

[runner]
magicEnabled = false
